/* Obsidianify Inbox - bundled build, see main.ts for source */

var u=Object.defineProperty;var F=Object.getOwnPropertyDescriptor;var S=Object.getOwnPropertyNames;var I=Object.prototype.hasOwnProperty;var A=(r,c)=>{for(var t in c)u(r,t,{get:c[t],enumerable:!0})},T=(r,c,t,s)=>{if(c&&typeof c=="object"||typeof c=="function")for(let e of S(c))!I.call(r,e)&&e!==t&&u(r,e,{get:()=>c[e],enumerable:!(s=F(c,e))||s.enumerable});return r};var D=r=>T(u({},"__esModule",{value:!0}),r);var z={};A(z,{default:()=>g});module.exports=D(z);var i=require("obsidian"),O={inboxPath:"Inbox"},R=/^(\d{1,3}\.){3}\d{1,3}$/,B=/^[A-Za-z0-9][A-Za-z0-9.\-]*\.[A-Za-z]{2,}$/,C=/^(\/[^\s]+|[A-Za-z]:\\[^\s]+)$/,L=/^[\w.\-]+@[\w.\-]+:\S*[#$]/,M="zmprov|grep|ssh|mount|ls|touch|dmesg|bash|openssl|curl|git|npm|docker|sudo|cd|cat|chmod|chown|systemctl|journalctl|ping|traceroute|nslookup|dig|yum|apt-get|apt|netstat|ss|ip|ifconfig|tail|head|vim|nano|ps|kill|df|du|tar|scp|rsync|wget|python3?|pip3?|vssadmin|powershell|reg|sc|tasklist|taskkill|iptables|firewall-cmd",w=new RegExp(`^(${M})\\b`),_=/^(.{1,60}):$/;function G(r){let c=r.trim().split(/(?:\r?\n){2,}/),t=[];for(let s of c){let e=s.split(/\r?\n/),n=[],a=[],l=()=>{a.length>0&&(n.push("```",...a,"```"),a=[])};for(let h of e){let o=h.trim();if(o===""){l(),n.push("");continue}let p=o.match(_);if(p&&!w.test(o)){l(),n.push(`## ${p[1].trim()}`);continue}if(w.test(o)||L.test(o)){a.push(o);continue}l(),R.test(o)||B.test(o)||C.test(o)?n.push(`\`${o}\``):n.push(o)}l(),t.push(n.join(`
`))}return t.join(`

`)}function v(r){return r.replace(/[\\/:*?"<>|]/g,"-").trim()}var f=class extends i.Modal{constructor(t,s,e,n){super(t);this.result=null;this.submitted=!1;this.fileLabel=s,this.categories=e,this.onSubmit=n}onOpen(){let{contentEl:t}=this;t.createEl("h3",{text:"Choose a category"}),t.createEl("p",{text:this.fileLabel});let s=t.createEl("input",{type:"text",attr:{list:"obsidianify-categories",placeholder:"Type or pick a category..."}});s.style.width="100%";let e=t.createEl("datalist");e.id="obsidianify-categories";for(let h of this.categories)e.createEl("option",{value:h});s.focus();let n=t.createDiv();n.style.marginTop="1em",n.style.display="flex",n.style.justifyContent="flex-end",n.style.gap="0.5em";let a=n.createEl("button",{text:"Skip this file"});a.onclick=()=>{this.result=null,this.close()};let l=n.createEl("button",{text:"OK",cls:"mod-cta"});l.onclick=()=>{this.result=s.value.trim(),this.close()},s.addEventListener("keydown",h=>{h.key==="Enter"&&(this.result=s.value.trim(),this.close())})}onClose(){this.contentEl.empty(),this.submitted||(this.submitted=!0,this.onSubmit(this.result))}},g=class extends i.Plugin{constructor(){super(...arguments);this.processingFiles=new Set}async onload(){await this.loadSettings(),this.addCommand({id:"process-inbox",name:"Process Inbox folder",callback:()=>this.processInbox()}),this.addRibbonIcon("inbox","Process Obsidianify Inbox",()=>this.processInbox()),this.addSettingTab(new b(this.app,this)),this.registerEvent(this.app.vault.on("create",t=>{t instanceof i.TFile&&t.extension==="txt"&&this.isInInbox(t)&&setTimeout(()=>this.processFile(t),300)}))}isInInbox(t){var e;let s=(0,i.normalizePath)(this.settings.inboxPath);return((e=t.parent)==null?void 0:e.path)===s}getExistingCategories(){let t=this.app.vault.getRoot(),s=[];for(let e of t.children)e instanceof i.TFolder&&e.name!==this.settings.inboxPath&&!e.name.startsWith(".")&&s.push(e.name);return s.sort()}async processInbox(){let t=(0,i.normalizePath)(this.settings.inboxPath),s=this.app.vault.getAbstractFileByPath(t);if(!(s instanceof i.TFolder)){new i.Notice(`Inbox folder "${this.settings.inboxPath}" not found.`);return}let e=s.children.filter(h=>h instanceof i.TFile&&h.extension==="txt");if(e.length===0){new i.Notice("No .txt files in Inbox.");return}let n=0,a=0,l=0;for(let h of e){let o=await this.processFile(h);o==="created"?n++:o==="skipped"?a++:o==="failed"&&l++}new i.Notice(`Obsidianify: ${n} created, ${a} skipped, ${l} failed.`)}async processFile(t){if(this.processingFiles.has(t.path))return"busy";this.processingFiles.add(t.path);try{let s=this.getExistingCategories(),e=await new Promise(d=>{new f(this.app,t.name,s,d).open()});if(e===null)return"skipped";let n=await this.app.vault.read(t),a=t.basename,l=v(a),h=G(n),o=(0,i.moment)().format("YYYY-MM-DDTHH:mm:ss"),p="",m="tags: []";if(e!==""){let d=v(e);p=d,m=`tags: [${d}]`;let P=(0,i.normalizePath)(p);this.app.vault.getAbstractFileByPath(P)||await this.app.vault.createFolder(P)}let $=`---
title: "${a}"
created: ${o}
aliases: []
${m}
source: "${t.name}"
summary: ""
---

# ${a}

---

`,E=await this.getUniquePath(p,l,".md");await this.app.vault.create(E,$+h);let y=`${this.settings.inboxPath}/Processed`,x=(0,i.normalizePath)(y);this.app.vault.getAbstractFileByPath(x)||await this.app.vault.createFolder(x);let k=await this.getUniquePath(y,l,".txt");return await this.app.vault.rename(t,k),"created"}catch(s){return new i.Notice(`Failed to convert ${t.name}: ${s}`),"failed"}finally{this.processingFiles.delete(t.path)}}async getUniquePath(t,s,e){let n=(0,i.normalizePath)(t?`${t}/${s}${e}`:`${s}${e}`),a=2;for(;this.app.vault.getAbstractFileByPath(n);)n=(0,i.normalizePath)(t?`${t}/${s} (${a})${e}`:`${s} (${a})${e}`),a++;return n}async loadSettings(){this.settings=Object.assign({},O,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}},b=class extends i.PluginSettingTab{constructor(t,s){super(t,s);this.plugin=s}display(){let{containerEl:t}=this;t.empty(),new i.Setting(t).setName("Inbox folder").setDesc("Vault folder to watch for .txt files. Save or share files into this folder to convert them into notes.").addText(s=>s.setPlaceholder("Inbox").setValue(this.plugin.settings.inboxPath).onChange(async e=>{this.plugin.settings.inboxPath=e||"Inbox",await this.plugin.saveSettings()}))}};
